Multi-app droplet (#7)
* A reminder of where I left off...

* Initial web view

* Initial work to add revel. Leftover gmux. Cleanup required.

* Additional gmux changes. Will be reverting this.

* Revert "Additional gmux changes. Will be reverting this."

This reverts commit 09ff36ba67fd1d475950a1a665b4fb44938b644b.

* Revert "Initial web view"

This reverts commit 7759fb2ffb94a6761ba4af2921583e056186f6be.

* Revert "Initial work to add revel. Leftover gmux. Cleanup required."

This reverts commit 6008f6e271887b7cd3807caf41342052187bf85f.

* go mod tidy

* Trying Fiber https://github.com/gofiber/fiber

* Trying to reuse the SerializeMailbox. Confused why this duplication
exists and hoping I having fucked something up.

* Linting error

* Forgot to commit the definition of the variable

* Node version CI setup

* Seperating the NPM requirement from the rest of go build

* Dockerfile image which supports both Go and Node.

* Makefile run args

* WIP Fiber

* Adding in support for passing the file manager in to the fiber context

* First pass at moving to multiple docker images.

* Trying to resolve CI "Cannot open: File exists" error

--
->
prepare environment
  Checking for go.mod: go.mod
  Received 187493436 of 216853564 (86.5%), 179.0 MBs/sec
  Cache Size: ~207 MB (216853564 B)
  /usr/bin/tar -xf /home/runner/work/_temp/9cd11469-dab1-40a5-99ae-c2a3759a9ae7/cache.tzst -P -C /home/runner/work/postmanpat/postmanpat --use-compress-program unzstd
  Error: /usr/bin/tar: ../../../go/pkg/mod/go.uber.org/mock@v0.4.0/gomock/callset.go: Cannot open: File exists

* V2 Trying to resolve CI "Cannot open: File exists" error

* V3 Trying to resolve CI "Cannot open: File exists" error

* Adding nolint:errcheck

* Working through the CI errors

* Second pass at moving to multiple docker images.

* Moving over to docker-compose

* Working on the switch over to docker compose and the webhooks for new
images